from PyQt5 import QtCore, QtGui, QtWidgets
from pin import Ui_PinWindow
import backend
import code_builder

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.setFixedSize(589, 360)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(270, 10, 301, 301))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 239, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 239, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 239, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 239, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.frame.setPalette(palette)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(210, 10, 80, 80))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame)
        self.pushButton_8.setGeometry(QtCore.QRect(110, 210, 80, 80))
        self.pushButton_8.setStyleSheet("")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame)
        self.pushButton_5.setGeometry(QtCore.QRect(110, 110, 80, 80))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame)
        self.pushButton_7.setGeometry(QtCore.QRect(10, 210, 80, 80))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(110, 10, 80, 80))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_9 = QtWidgets.QPushButton(self.frame)
        self.pushButton_9.setGeometry(QtCore.QRect(210, 210, 80, 80))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame)
        self.pushButton_6.setGeometry(QtCore.QRect(210, 110, 80, 80))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_1 = QtWidgets.QPushButton(self.frame)
        self.pushButton_1.setGeometry(QtCore.QRect(10, 10, 80, 80))
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 110, 80, 80))
        self.pushButton_4.setObjectName("pushButton_4")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(20, 110, 231, 91))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(10, 10, 211, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(80, 50, 71, 31))
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(20, 240, 231, 71))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_10.setGeometry(QtCore.QRect(20, 20, 88, 27))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_11.setGeometry(QtCore.QRect(120, 20, 88, 27))
        self.pushButton_11.setObjectName("pushButton_11")
        self.verify_btn = QtWidgets.QPushButton(self.centralwidget)
        self.verify_btn.setGeometry(QtCore.QRect(50, 30, 71, 51))
        self.verify_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.verify_btn.setStyleSheet("image: url(:/verify_svg/Group 2.svg);\n"
"border-radius:1;\n"
"")
        self.verify_btn.setText("")
        self.verify_btn.clicked.connect(code_builder.code_builder)
        self.verify_btn.setObjectName("verify_btn")
        self.upload_btn = QtWidgets.QPushButton(self.centralwidget)
        self.upload_btn.setGeometry(QtCore.QRect(150, 30, 71, 51))
        self.upload_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.upload_btn.setStyleSheet("image: url(:/upload/uploadupload.svg);\n"
"border-radius: 1;")
        self.upload_btn.setText("")
        self.upload_btn.setObjectName("upload_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 589, 24))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuDetect_Controller = QtWidgets.QMenu(self.menubar)
        self.menuDetect_Controller.setObjectName("menuDetect_Controller")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionImport_Config = QtWidgets.QAction(MainWindow)
        self.actionImport_Config.setObjectName("actionImport_Config")
        self.actionExport_Config = QtWidgets.QAction(MainWindow)
        self.actionExport_Config.setObjectName("actionExport_Config")
        self.actionDetect_Controller = QtWidgets.QAction(MainWindow)
        self.actionDetect_Controller.setObjectName("actionDetect_Controller")
        self.actionVerify_Layout = QtWidgets.QAction(MainWindow)
        self.actionVerify_Layout.setObjectName("actionVerify_Layout")
        self.menuFile.addAction(self.actionImport_Config)
        self.menuFile.addAction(self.actionExport_Config)
        self.menuDetect_Controller.addAction(self.actionDetect_Controller)
        self.menuDetect_Controller.addAction(self.actionVerify_Layout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuDetect_Controller.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_3.setText(_translate("MainWindow", "3"))
        self.pushButton_8.setText(_translate("MainWindow", "8"))
        self.pushButton_5.setText(_translate("MainWindow", "5"))
        self.pushButton_7.setText(_translate("MainWindow", "7"))
        self.pushButton_2.setText(_translate("MainWindow", "2"))
        self.pushButton_9.setText(_translate("MainWindow", "9"))
        self.pushButton_6.setText(_translate("MainWindow", "6"))
        self.pushButton_1.setText(_translate("MainWindow", "1"))
        self.pushButton_4.setText(_translate("MainWindow", "4"))
        self.label.setText(_translate("MainWindow", "Microcontroller Connected to: "))
        self.label_2.setText(_translate("MainWindow", "None"))
        self.pushButton_10.setText(_translate("MainWindow", "control 1"))
        self.pushButton_11.setText(_translate("MainWindow", "control 2"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuDetect_Controller.setTitle(_translate("MainWindow", "Tools"))
        self.actionImport_Config.setText(_translate("MainWindow", "Import Config"))
        self.actionImport_Config.triggered.connect(backend.import_config)
        self.actionExport_Config.setText(_translate("MainWindow", "Export Config"))
        self.actionExport_Config.triggered.connect(backend.export_config)
        self.actionDetect_Controller.setText(_translate("MainWindow", "Detect Controller"))
        self.actionVerify_Layout.setText(_translate("MainWindow", "Verify Layout"))
        self.actionVerify_Layout.triggered.connect(backend.verify_layout)

class MainWindow(QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.pushButton_1.clicked.connect(lambda: self.open_second_window(1))
        self.pushButton_2.clicked.connect(lambda: self.open_second_window(2))
        self.pushButton_3.clicked.connect(lambda: self.open_second_window(3))
        self.pushButton_4.clicked.connect(lambda: self.open_second_window(4))
        self.pushButton_5.clicked.connect(lambda: self.open_second_window(5))
        self.pushButton_6.clicked.connect(lambda: self.open_second_window(6))
        self.pushButton_7.clicked.connect(lambda: self.open_second_window(7))
        self.pushButton_8.clicked.connect(lambda: self.open_second_window(8))
        self.pushButton_9.clicked.connect(lambda: self.open_second_window(9))
        self.actionDetect_Controller.triggered.connect(self.get_port_action)
        self.pushButton_10.clicked.connect(lambda:[backend.encoder_command("1")])
        self.pushButton_11.clicked.connect(lambda:[backend.encoder_command("2")])

    def open_second_window(self, switch_number):
        if not hasattr(self, 'second_window') or not self.second_window.isVisible():
            self.second_window = QtWidgets.QMainWindow()
            self.ui = Ui_PinWindow(switch_number)
            self.ui.setupUi(self.second_window)
            self.second_window.show()

    def get_port_action(self):
        backend.get_com_ports()
        self.label_2.setText(backend.com_port_selected)

import main_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = MainWindow()
    MainWindow.show()
    sys.exit(app.exec_())